"use strict";
const $=id=>document.getElementById(id), n=id=>Number($(id).value), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={nodes:[],pipes:[],elements:[],results:null};
const DN=[32,40,50,63,75,90,110,125,140,160,180,200,225,250,280,315,355,400,450,500,560,630];
function xy(p){return $('coordOrder').value==='NE'?{e:p.y,n:p.x}:{e:p.x,n:p.y}}
function dist(a,b){const A=xy(a),B=xy(b);return Math.hypot(B.e-A.e,B.n-A.n)}
function download(name,text,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function sample(){state.nodes=[
{id:'R-01',x:7450000,y:4700000,z:515,parent:'',pop:0,type:'RESERVOIR',desc:'Rezervuari kryesor'},
{id:'N-01',x:7450150,y:4699950,z:500,parent:'R-01',pop:150,type:'JUNCTION',desc:'Nyja kryesore'},
{id:'N-02',x:7450310,y:4699880,z:485,parent:'N-01',pop:300,type:'JUNCTION',desc:'Lagjja A'},
{id:'N-03',x:7450480,y:4699800,z:470,parent:'N-02',pop:350,type:'END',desc:'Fund dege A'},
{id:'N-04',x:7450250,y:4700100,z:490,parent:'N-01',pop:250,type:'JUNCTION',desc:'Degëzim B'},
{id:'N-05',x:7450420,y:4700180,z:455,parent:'N-04',pop:300,type:'END',desc:'Fund dege B'},
{id:'N-06',x:7450080,y:4700200,z:505,parent:'R-01',pop:150,type:'JUNCTION',desc:'Degëzim C'},
{id:'N-07',x:7450200,y:4700350,z:525,parent:'N-06',pop:0,type:'END',desc:'Zonë e lartë'}];renderNodes();}
function renderNodes(){const tb=$('nodesTable').tBodies[0];tb.innerHTML='';state.nodes.forEach((p,i)=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${i+1}</td>${['id','x','y','z','parent','pop'].map(k=>`<td><input data-i="${i}" data-k="${k}" ${['x','y','z','pop'].includes(k)?'type="number" step="0.01"':''} value="${esc(p[k])}"></td>`).join('')}<td><select data-i="${i}" data-k="type">${['RESERVOIR','JUNCTION','END'].map(v=>`<option ${p.type===v?'selected':''}>${v}</option>`).join('')}</select></td><td><input data-i="${i}" data-k="desc" value="${esc(p.desc)}"></td><td><button data-del="${i}">Fshi</button></td>`;tb.appendChild(tr)});tb.querySelectorAll('[data-k]').forEach(el=>el.onchange=e=>{const i=+e.target.dataset.i,k=e.target.dataset.k;state.nodes[i][k]=['x','y','z','pop'].includes(k)?Number(e.target.value):e.target.value});tb.querySelectorAll('[data-del]').forEach(b=>b.onclick=e=>{state.nodes.splice(+e.target.dataset.del,1);renderNodes()});$('importMsg').innerHTML=`<p class="ok">${state.nodes.length} nyje të ngarkuara.</p>`}
function parse(text){
  const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim()&&!x.trim().startsWith('#'));
  const out=[];
  let autoNo=1;
  for(const raw of lines){
    const line=raw.trim();
    // Pranon presje, pikëpresje, TAB ose një/më shumë hapësira.
    const c=(line.includes(';')?line.split(';'):line.includes(',')?line.split(','):line.split(/\s+/))
      .map(x=>x.trim().replace(/^"|"$/g,''));
    if(!c.length)continue;
    const joined=c.join(' ').toLowerCase();
    if(/(^|\s)(id|point|nr)(\s|$)/.test(joined) && /(x|easting)/.test(joined) && /(y|northing)/.test(joined))continue;

    let id,x,y,z,parent='',pop=0,type='JUNCTION',desc='',rest=[];
    // Formati i plotë: ID X Y Z Parent Population Type Description
    if(c.length>=4 && !Number.isFinite(Number(c[0]))){
      [id,x,y,z,parent='',pop=0,type='JUNCTION',...rest]=c;
      desc=rest.join(' ');
    }
    // Formati i thjeshtë: X Y Z [Description]
    else if(c.length>=3 && [c[0],c[1],c[2]].every(v=>Number.isFinite(Number(v)))){
      id=`N-${String(autoNo).padStart(2,'0')}`;
      [x,y,z,...rest]=c;
      desc=rest.join(' ');
      parent=out.length?out[out.length-1].id:'';
      type=out.length?'JUNCTION':'RESERVOIR';
    }
    // Formati: ID X Y Z, ku ID mund të jetë numerik
    else if(c.length>=4 && [c[1],c[2],c[3]].every(v=>Number.isFinite(Number(v)))){
      [id,x,y,z,...rest]=c;
      desc=rest.join(' ');
      parent=out.length?out[out.length-1].id:'';
      type=out.length?'JUNCTION':'RESERVOIR';
    } else continue;

    if([x,y,z].every(v=>Number.isFinite(Number(v)))){
      out.push({id:String(id||`N-${String(autoNo).padStart(2,'0')}`),x:+x,y:+y,z:+z,parent:String(parent||''),pop:+pop||0,type:(type||'JUNCTION').toUpperCase(),desc});
      autoNo++;
    }
  }
  if(out.length<2)throw Error('Nuk u lexuan së paku dy pika. Përdor formatin ID, X, Y, Z, Parent, Population, Type, Description ose thjesht X Y Z.');
  return out
}
function childrenMap(){const m={};state.nodes.forEach(x=>m[x.id]=[]);state.nodes.forEach(x=>{if(x.parent&&m[x.parent])m[x.parent].push(x.id)});return m}
function descendantsPop(id,map,nodeMap,memo={}){if(memo[id]!=null)return memo[id];const nd=nodeMap[id];return memo[id]=(nd.pop||0)+(map[id]||[]).reduce((s,c)=>s+descendantsPop(c,map,nodeMap,memo),0)}
function hazen(Qls,L,Dmm,C){const Q=Qls/1000,D=Dmm/1000;return Q<=0?0:10.67*L*Math.pow(Q,1.852)/(Math.pow(C,1.852)*Math.pow(D,4.871))}
function selectDn(q,L,C,vmin,vmax,dnMin){for(const dn of DN.filter(x=>x>=dnMin)){const A=Math.PI*Math.pow(dn/1000,2)/4,v=(q/1000)/A,hf=hazen(q,L,dn,C);if(v<=vmax)return{dn,v,hf,status:v<vmin?'Shpejtësi e ulët':'Në rregull'}}const dn=DN.at(-1),A=Math.PI*Math.pow(dn/1000,2)/4;return{dn,v:(q/1000)/A,hf:hazen(q,L,dn,C),status:'Kërkon DN më të madh'}}
function calculate(){try{if(state.nodes.length<2)throw Error('Ngarko rrjetin.');const nodeMap=Object.fromEntries(state.nodes.map(x=>[x.id,x]));const roots=state.nodes.filter(x=>!x.parent||x.type==='RESERVOIR');if(!roots.length)throw Error('Nuk u gjet nyja RESERVOIR.');for(const x of state.nodes)if(x.parent&&!nodeMap[x.parent])throw Error(`Parent ${x.parent} i nyjës ${x.id} nuk ekziston.`);const map=childrenMap(),projected=n('population')*Math.pow(1+n('growth')/100,n('years')),totalAssigned=state.nodes.reduce((s,x)=>s+(x.pop||0),0),scale=totalAssigned>0?projected/totalAssigned:0;state.nodes.forEach(x=>x.designPop=(x.pop||0)*scale);const demandPerPerson=n('consumption')*(1+n('losses')/100)*n('maxDay')*n('maxHour')/86400;const memo={};function dpop(id){if(memo[id]!=null)return memo[id];return memo[id]=(nodeMap[id].designPop||0)+(map[id]||[]).reduce((s,c)=>s+dpop(c),0)}
const reservoir=roots[0],H=n('reservoirLevel');state.pipes=[];state.elements=[];const pressure={[reservoir.id]:H-reservoir.z};const ordered=[];function walk(id){for(const cid of map[id]||[]){ordered.push([id,cid]);walk(cid)}}walk(reservoir.id);for(const [pid,cid] of ordered){const a=nodeMap[pid],b=nodeMap[cid],L=dist(a,b),q=dpop(cid)*demandPerPerson,sel=selectDn(q,L,n('hazenC'),n('vmin'),n('vmax'),n('dnMin')),parentHead=(a.head??H),head=parentHead-sel.hf,p=head-b.z;b.head=head;pressure[b.id]=p;let status=sel.status;if(p<n('minPressure'))status+='; presion i pamjaftueshëm';if(p>n('maxPressure'))status+='; presion i lartë';state.pipes.push({id:`${pid}-${cid}`,from:pid,to:cid,L,q,...sel,startHead:parentHead,endHead:head,pressure:p,status})}
for(const x of state.nodes){const p=pressure[x.id]??0;if(x.type!=='RESERVOIR'&&p>n('maxPressure'))state.elements.push(el('PRV',x,`Rregullator presioni; presioni statik ${p.toFixed(1)} m, synim rreth ${n('maxPressure')} m`));if(x.type!=='RESERVOIR'&&p<n('minPressure')){const head=n('minPressure')-p+5,power=(9.81*(dpop(x.id)*demandPerPerson/1000)*head)/(n('pumpEff')/100);state.elements.push(el('PUMP',x,`Stacion pompimi orientues: Q=${(dpop(x.id)*demandPerPerson).toFixed(2)} l/s, H=${head.toFixed(1)} m, P≈${power.toFixed(2)} kW`))}if((map[x.id]||[]).length>1)state.elements.push(el('ISOLATION_VALVE',x,'Valvula mbyllëse në secilën degë të nyjës'));if(x.type==='END')state.elements.push(el('WASHOUT',x,'Shkarkues në fund të degës / pikë të ulët'))}
for(const [pid,cid] of ordered){const a=nodeMap[pid],b=nodeMap[cid];if(b.z>a.z&&!(map[cid]||[]).some(k=>nodeMap[k].z>b.z))state.elements.push(el('AIR_VALVE',b,'Valvul ajri në pikë të lartë lokale'))}
const dailyMax=projected*n('consumption')*(1+n('losses')/100)*n('maxDay')/1000,resVol=dailyMax*n('storagePercent')/100+n('fireReserve');state.results={projected,dailyMax,resVol,peakFlow:projected*demandPerPerson,totalLength:state.pipes.reduce((s,p)=>s+p.L,0),pumpCount:state.elements.filter(x=>x.type==='PUMP').length};renderAll();$('msg').innerHTML='<p class="ok">Projektimi u gjenerua.</p>';show('results')}catch(e){$('msg').innerHTML=`<p class="bad">${esc(e.message)}</p>`}}
function el(type,node,note){const c=xy(node);return{id:`${type}-${node.id}`,type,node:node.id,e:c.e,n:c.n,z:node.z,note}}
function renderAll(){renderPlan();renderBranches();renderResults()}
function renderPlan(){const s=$('planSvg');s.innerHTML='';const pts=state.nodes.map(xy),minE=Math.min(...pts.map(p=>p.e)),maxE=Math.max(...pts.map(p=>p.e)),minN=Math.min(...pts.map(p=>p.n)),maxN=Math.max(...pts.map(p=>p.n)),pad=60,W=1100,H=650,fx=e=>pad+(e-minE)/(maxE-minE||1)*(W-2*pad),fy=n=>H-pad-(n-minN)/(maxN-minN||1)*(H-2*pad);state.pipes.forEach(p=>{const a=xy(state.nodes.find(x=>x.id===p.from)),b=xy(state.nodes.find(x=>x.id===p.to));s.insertAdjacentHTML('beforeend',`<line x1="${fx(a.e)}" y1="${fy(a.n)}" x2="${fx(b.e)}" y2="${fy(b.n)}" stroke="#087b8c" stroke-width="4"/><text x="${(fx(a.e)+fx(b.e))/2}" y="${(fy(a.n)+fy(b.n))/2-6}" font-size="12">DN${p.dn}</text>`)});state.nodes.forEach(x=>{const p=xy(x),r=x.type==='RESERVOIR'?12:8;s.insertAdjacentHTML('beforeend',`<circle cx="${fx(p.e)}" cy="${fy(p.n)}" r="${r}" fill="white" stroke="#b7281c" stroke-width="4"/><text x="${fx(p.e)+10}" y="${fy(p.n)-10}" font-weight="bold">${esc(x.id)}</text>`)});}
function pathsToLeaves(){const map=childrenMap(),root=state.nodes.find(x=>x.type==='RESERVOIR'||!x.parent);const out=[];function rec(id,path){const ch=map[id]||[];if(!ch.length)out.push([...path,id]);else ch.forEach(c=>rec(c,[...path,id]))}rec(root.id,[]);return out}
function renderBranches(){const sel=$('branchSelect'),paths=pathsToLeaves();sel.innerHTML=paths.map((p,i)=>`<option value="${i}">${p.join(' → ')}</option>`).join('');sel.onchange=renderProfile;renderProfile()}
function renderProfile(){if(!state.results)return;const paths=pathsToLeaves(),path=paths[+$('branchSelect').value||0]||paths[0];if(!path)return;let ch=0;const arr=path.map((id,i)=>{const nd=state.nodes.find(x=>x.id===id);if(i)ch+=dist(state.nodes.find(x=>x.id===path[i-1]),nd);return{...nd,ch,head:nd.head??n('reservoirLevel')}});const s=$('profileSvg');s.innerHTML='';const W=1100,H=620,pad=70,minZ=Math.min(...arr.flatMap(x=>[x.z,x.head]))-5,maxZ=Math.max(...arr.flatMap(x=>[x.z,x.head]))+5,maxCh=arr.at(-1).ch||1,fx=x=>pad+x/maxCh*(W-2*pad),fy=z=>H-pad-(z-minZ)/(maxZ-minZ)*(H-2*pad);for(let i=0;i<=10;i++){const z=minZ+(maxZ-minZ)*i/10;s.insertAdjacentHTML('beforeend',`<line x1="${pad}" y1="${fy(z)}" x2="${W-pad}" y2="${fy(z)}" stroke="#dce7eb"/><text x="8" y="${fy(z)+4}" font-size="11">${z.toFixed(1)}</text>`)}const terrain=arr.map(x=>`${fx(x.ch)},${fy(x.z)}`).join(' '),hyd=arr.map(x=>`${fx(x.ch)},${fy(x.head)}`).join(' ');s.insertAdjacentHTML('beforeend',`<polyline points="${terrain}" fill="none" stroke="#604020" stroke-width="3"/><polyline points="${hyd}" fill="none" stroke="#087b8c" stroke-width="3"/>`);arr.forEach(x=>s.insertAdjacentHTML('beforeend',`<circle cx="${fx(x.ch)}" cy="${fy(x.z)}" r="5" fill="white" stroke="#b7281c"/><text x="${fx(x.ch)+6}" y="${fy(x.z)-7}" font-size="11">${x.id}</text>`));s.insertAdjacentHTML('beforeend',`<text x="${pad}" y="25" font-weight="bold">Terreni (kafe) dhe vija piezometrike (kaltër) – ${esc(path.join(' → '))}</text>`)}
function renderResults(){const r=state.results;$('cards').innerHTML=[['Popullsia projektuese',r.projected.toFixed(0)+' banorë'],['Vëllimi orientues i rezervuarit',r.resVol.toFixed(1)+' m³'],['Q ditës max.',r.dailyMax.toFixed(1)+' m³/ditë'],['Q orës max.',r.peakFlow.toFixed(2)+' l/s'],['Gjatësia totale',r.totalLength.toFixed(1)+' m'],['Stacione pompimi',r.pumpCount]].map(x=>`<div class="card">${x[0]}<b>${x[1]}</b></div>`).join('');$('elementsTable').tBodies[0].innerHTML=state.elements.map(e=>`<tr><td>${e.id}</td><td>${e.type}</td><td>${e.node}</td><td>${e.e.toFixed(3)}</td><td>${e.n.toFixed(3)}</td><td>${e.z.toFixed(3)}</td><td>${esc(e.note)}</td></tr>`).join('');$('pipesTable').tBodies[0].innerHTML=state.pipes.map(p=>`<tr><td>${p.id}</td><td>${p.L.toFixed(2)}</td><td>${p.q.toFixed(2)}</td><td>${p.dn}</td><td>${p.v.toFixed(2)}</td><td>${p.hf.toFixed(2)}</td><td>${p.pressure.toFixed(1)}</td><td>${esc(p.status)}</td></tr>`).join('')}
function show(id){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.id===id))}
function csvNodes(){if(!state.results)return alert('Gjenero projektin.');let rows=['Point,Easting,Northing,Elevation,Code,Description'];state.nodes.forEach(x=>{const p=xy(x);rows.push(`${x.id},${p.e.toFixed(3)},${p.n.toFixed(3)},${x.z.toFixed(3)},NODE,"${x.desc||x.type}"`)});state.elements.forEach(e=>rows.push(`${e.id},${e.e.toFixed(3)},${e.n.toFixed(3)},${e.z.toFixed(3)},${e.type},"${e.note}"`));download('elementet_piketim_PNEZD.csv',rows.join('\n'),'text/csv')}
function csvPipes(){let rows=['Segment,From,To,Length_m,Flow_lps,DN_mm,Velocity_mps,Headloss_m,EndPressure_m,Status'];state.pipes.forEach(p=>rows.push([p.id,p.from,p.to,p.L.toFixed(3),p.q.toFixed(3),p.dn,p.v.toFixed(3),p.hf.toFixed(3),p.pressure.toFixed(3),`"${p.status}"`].join(',')));download('gypat.csv',rows.join('\n'),'text/csv')}
function geo(){const feats=[];state.nodes.forEach(x=>{const p=xy(x);feats.push({type:'Feature',properties:{id:x.id,type:x.type,pop:x.designPop,description:x.desc},geometry:{type:'Point',coordinates:[p.e,p.n,x.z]}})});state.elements.forEach(e=>feats.push({type:'Feature',properties:{id:e.id,type:e.type,node:e.node,note:e.note},geometry:{type:'Point',coordinates:[e.e,e.n,e.z]}}));state.pipes.forEach(p=>{const a=state.nodes.find(x=>x.id===p.from),b=state.nodes.find(x=>x.id===p.to),A=xy(a),B=xy(b);feats.push({type:'Feature',properties:{id:p.id,dn:p.dn,q_lps:p.q,velocity:p.v,headloss:p.hf},geometry:{type:'LineString',coordinates:[[A.e,A.n,a.z],[B.e,B.n,b.z]]}})});download('HydroDesign_KOSOVAREF01.geojson',JSON.stringify({type:'FeatureCollection',name:'HydroDesign',crs:{type:'name',properties:{name:'EPSG:9141'}},features:feats},null,2),'application/geo+json')}
function dxf(){let t='0\nSECTION\n2\nHEADER\n9\n$ACADVER\n1\nAC1015\n0\nENDSEC\n0\nSECTION\n2\nENTITIES\n';state.pipes.forEach(p=>{const a=state.nodes.find(x=>x.id===p.from),b=state.nodes.find(x=>x.id===p.to),A=xy(a),B=xy(b);t+=`0\nLINE\n8\nPIPES_DN${p.dn}\n10\n${A.e}\n20\n${A.n}\n30\n${a.z}\n11\n${B.e}\n21\n${B.n}\n31\n${b.z}\n`});[...state.nodes.map(x=>{const p=xy(x);return{id:x.id,e:p.e,n:p.n,z:x.z,type:x.type}}),...state.elements].forEach(e=>{t+=`0\nPOINT\n8\n${e.type}\n10\n${e.e}\n20\n${e.n}\n30\n${e.z}\n0\nTEXT\n8\nLABELS\n10\n${e.e+1}\n20\n${e.n+1}\n30\n${e.z}\n40\n2\n1\n${e.id}\n`});t+='0\nENDSEC\n0\nEOF\n';download('HydroDesign_3D_KOSOVAREF01.dxf',t,'application/dxf')}
function land(){const pts=state.nodes.map(x=>{const p=xy(x);return`<CgPoint name="${esc(x.id)}">${p.n.toFixed(3)} ${p.e.toFixed(3)} ${x.z.toFixed(3)}</CgPoint>`}).join('');const lines=state.pipes.map(p=>{const a=state.nodes.find(x=>x.id===p.from),b=state.nodes.find(x=>x.id===p.to),A=xy(a),B=xy(b);return`<Parcel name="${p.id}" desc="DN${p.dn}"><CoordGeom><Line><Start>${A.n} ${A.e}</Start><End>${B.n} ${B.e}</End></Line></CoordGeom></Parcel>`}).join('');download('HydroDesign_LandXML.xml',`<?xml version="1.0"?><LandXML xmlns="http://www.landxml.org/schema/LandXML-1.2" version="1.2" date="${new Date().toISOString().slice(0,10)}"><Units><Metric linearUnit="meter" areaUnit="squareMeter" volumeUnit="cubicMeter"/></Units><CoordinateSystem name="KOSOVAREF01" epsgCode="9141"/><CgPoints>${pts}</CgPoints><Parcels>${lines}</Parcels></LandXML>`,'application/xml')}
function save(){localStorage.setItem('hydrodesign',JSON.stringify({nodes:state.nodes,inputs:[...document.querySelectorAll('aside input,aside select')].reduce((o,e)=>(e.id&&(o[e.id]=e.value),o),{})}));alert('U ruajt lokalisht.')}function load(){const d=JSON.parse(localStorage.getItem('hydrodesign')||'null');if(!d)return alert('Nuk ka projekt të ruajtur.');state.nodes=d.nodes||[];Object.entries(d.inputs||{}).forEach(([k,v])=>{$(k)&&($(k).value=v)});renderNodes()}
function exportJson(){download('HydroDesign_project.json',JSON.stringify({inputs:[...document.querySelectorAll('aside input,aside select')].reduce((o,e)=>(e.id&&(o[e.id]=e.value),o),{}),nodes:state.nodes,pipes:state.pipes,elements:state.elements,results:state.results},null,2),'application/json')}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>show(b.dataset.tab));$('sampleBtn').onclick=sample;$('addBtn').onclick=()=>{state.nodes.push({id:`N-${String(state.nodes.length+1).padStart(2,'0')}`,x:0,y:0,z:0,parent:'',pop:0,type:'JUNCTION',desc:''});renderNodes()};$('fileInput').onchange=async e=>{try{state.nodes=parse(await e.target.files[0].text());renderNodes()}catch(err){alert(err.message)}};$('calcBtn').onclick=calculate;$('csvNodesBtn').onclick=csvNodes;$('csvPipesBtn').onclick=csvPipes;$('geoBtn').onclick=geo;$('dxfBtn').onclick=dxf;$('landBtn').onclick=land;$('pdfBtn').onclick=()=>window.print();$('saveBtn').onclick=save;$('loadBtn').onclick=load;$('jsonBtn').onclick=exportJson;$('newBtn').onclick=()=>{if(confirm('Të pastrohet projekti?')){state.nodes=[];state.pipes=[];state.elements=[];state.results=null;renderNodes()}};sample();
